
--------- AEROPORTO
CREATE TABLE AEROPORTO (
ID_AEROPORTO INTEGER NOT NULL PRIMARY KEY,
ID_CIDADE      NUMBER       not null
        constraint FK_ID_CIDADE
            references CIDADE
                on delete cascade,
NOME_AEROPORTO VARCHAR2(50) not null,
SIGLA          VARCHAR2(8)  not null
);

CREATE SEQUENCE ID_AEROPORTO_SEQ START WITH 001 INCREMENT BY 1 MAXVALUE 9999 NOCYCLE NOCACHE;

ALTER TABLE AEROPORTO
ADD CONSTRAINT FK_ID_CIDADE FOREIGN KEY(ID_CIDADE) REFERENCES CIDADE(ID_CIDADE);

ALTER TABLE aeroporto MODIFY (NOME_AEROPORTO VARCHAR2(50))