
--------- AEROPORTO
CREATE TABLE AEROPORTO (
ID_AEROPORTO INTEGER NOT NULL PRIMARY KEY,
ID_CIDADE INTEGER NOT NULL,
NOME_AEROPORTO VARCHAR(35) NOT NULL
);

CREATE SEQUENCE ID_AEROPORTO_SEQ START WITH 001 INCREMENT BY 1 MAXVALUE 9999 NOCYCLE NOCACHE;

ALTER TABLE AEROPORTO
ADD CONSTRAINT FK_ID_CIDADE FOREIGN KEY(ID_CIDADE) REFERENCES CIDADE(ID_CIDADE);
