
----------- AERONAVE
CREATE TABLE AERONAVE(
    MODELO VARCHAR(20) NOT NULL,
    NUM_IDENTIFICACAO VARCHAR(20) NOT NULL PRIMARY KEY ,
    FABRICANTE VARCHAR (20) NOT NULL,
    ANOFABRICACAO INTEGER NOT NULL,
    MAPA_ASSENTO INTEGER NOT NULL,
    COMPANHIA_AEREA INTEGER NOT NULL
);

ALTER TABLE AERONAVE
ADD CONSTRAINT FK_MAPA_ASSENTO FOREIGN KEY(MAPA_ASSENTO) REFERENCES MAPA_ASSENTO(ID_MAPA);

ALTER TABLE AERONAVE
ADD CONSTRAINT FK_COMPANHIA_AEREA FOREIGN KEY(COMPANHIA_AEREA) REFERENCES COMPANHIA_AEREA(ID_COMPANHIA);

