
create table TRECHO
(
    ID_TRECHO    NUMBER not null
        primary key,
    AERO_SAIDA   NUMBER not null
        constraint FK_AERO_SAIDA
            references AEROPORTO
                on delete cascade,
    AERO_CHEGADA NUMBER not null
        constraint FK_AERO_CHEGADA
            references AEROPORTO
                on delete cascade
)

create table AERONAVE
(
    MODELO            VARCHAR2(20) not null,
    NUM_IDENTIFICACAO VARCHAR2(20) not null,
    FABRICANTE        VARCHAR2(20) not null,
    ANO_FABRICACAO    NUMBER       not null,
    COMPANHIA_AEREA   NUMBER
        constraint FK_COMPANHIA_AEREA
            references COMPANHIA_AEREA
                on delete cascade,
    ID_AERONAVE       NUMBER       not null
        constraint PK_ID_AERONAVE
            primary key,
    NUMASSENTOS       NUMBER       not null
)

create table AEROPORTO
(
    ID_AEROPORTO   NUMBER        not null
        primary key,
    ID_CIDADE      NUMBER        not null
        constraint FK_ID_CIDADE
            references CIDADE
                on delete cascade,
    NOME_AEROPORTO VARCHAR2(150) not null,
    SIGLA          VARCHAR2(8)   not null
)

create table ASSENTO
(
    ID_ASSENTO NUMBER      not null
        constraint PK_ID_ASSENTO
            primary key,
    ID_VOO     NUMBER
        constraint FK_ID_VOO
            references VOO
                on delete cascade,
    CODIGO     VARCHAR2(3) not null,
    STATUS     VARCHAR2(15) default 'DISPONIVEL'
)

create table CIDADE
(
    ID_CIDADE   NUMBER       not null
        primary key,
    NOME_CIDADE VARCHAR2(35) not null
)

create table COMPANHIA_AEREA
(
    ID_COMPANHIA_AEREA NUMBER       not null,
    NOME_COMPANHIA     VARCHAR2(15) not null,
    primary key (ID_COMPANHIA)
)

create table METODO_PAGAMENTO
(
    ID_METODO_PAGAMENTO NUMBER       not null,
    NOME_METODO         VARCHAR2(20) not null,
    primary key (ID_METODO)
)

create table VENDA
(
    ID_VENDA         NUMBER       not null
        primary key,
    NOME_PASSAGEIRO  VARCHAR2(50) not null,
    EMAIL_PASSAGEIRO VARCHAR2(50) not null,
    ASSENTO          NUMBER       not null
        constraint FK_ASSENTO
            references ASSENTO
                on delete cascade,
    ID_VOO           NUMBER       not null
        constraint FK_VOO
            references VOO
                on delete cascade,
    PAGAMENTO        NUMBER       not null
        constraint FK_PAGAMENTO
            references METODO_PAGAMENTO
                on delete cascade
)

create table VOO
(
    ID_VOO       NUMBER      not null
        primary key,
    DATA         DATE        not null,
    TRECHO       NUMBER      not null
        constraint FK_TRECHO
            references TRECHO
                on delete cascade,
    HORA_PARTIDA VARCHAR2(5) not null,
    HORA_CHEGADA VARCHAR2(5) not null,
    PRECO        NUMBER(10)  not null,
    AERONAVE     NUMBER      not null
        constraint FK_AERONAVE
            references AERONAVE
                on delete cascade
)

-------- ALTERANDO FKS - METODO DELETE CASCADE

--------- AEROPORTO

-- Excluir fk
ALTER TABLE AEROPORTO DROP CONSTRAINT FK_ID_CIDADE;

--Adicionar metodo cascata
ALTER TABLE AEROPORTO ADD CONSTRAINT FK_ID_CIDADE FOREIGN KEY(ID_CIDADE) REFERENCES CIDADE(ID_CIDADE) ON DELETE CASCADE;

DELETE FROM CIDADE WHERE ID_CIDADE=7;

------ AERONAVE
--ALTER TABLE AERONAVE DROP CONSTRAINT FK_MAPA_ASSENTO;
--ALTER TABLE AERONAVE ADD CONSTRAINT FK_MAPA_ASSENTO FOREIGN KEY(MAPA_ASSENTO) REFERENCES MAPA_ASSENTO(ID_MAPA) ON DELETE CASCADE;

ALTER TABLE AERONAVE DROP CONSTRAINT FK_COMPANHIA_AEREA;
ALTER TABLE AERONAVE ADD CONSTRAINT FK_COMPANHIA_AEREA FOREIGN KEY(COMPANHIA_AEREA) REFERENCES COMPANHIA_AEREA(ID_COMPANHIA_AEREA) ON DELETE CASCADE;

------ TRECHO
ALTER TABLE TRECHO DROP CONSTRAINT FK_AERO_SAIDA;
ALTER TABLE TRECHO ADD CONSTRAINT FK_AERO_SAIDA FOREIGN KEY(AERO_SAIDA) REFERENCES AEROPORTO(ID_AEROPORTO) ON DELETE CASCADE;

ALTER TABLE TRECHO DROP CONSTRAINT FK_AERO_CHEGADA;
ALTER TABLE TRECHO ADD CONSTRAINT FK_AERO_CHEGADA FOREIGN KEY(AERO_CHEGADA) REFERENCES AEROPORTO(ID_AEROPORTO) ON DELETE CASCADE;

------ VOO
ALTER TABLE VOO DROP CONSTRAINT FK_TRECHO;
ALTER TABLE VOO ADD CONSTRAINT FK_TRECHO FOREIGN KEY(TRECHO) REFERENCES TRECHO(ID_TRECHO) ON DELETE CASCADE;

ALTER TABLE VOO ADD CONSTRAINT FK_AERONAVE FOREIGN KEY(AERONAVE) REFERENCES AERONAVE(ID_AERONAVE) ON DELETE CASCADE;
ALTER TABLE VOO DROP CONSTRAINT FK_AERONAVE;

ALTER TABLE VENDA ADD CONSTRAINT FK_VOO FOREIGN KEY(ID_VOO) REFERENCES VOO(ID_VOO) ON DELETE CASCADE;

------ VENDA
ALTER TABLE VENDA DROP CONSTRAINT FK_ID_VOO;
ALTER TABLE VOO ADD CONSTRAINT FK_ID_VOO FOREIGN KEY(ID_VOO) REFERENCES VOO(ID_VOO) ON DELETE CASCADE;

ALTER TABLE VENDA DROP CONSTRAINT FK_ASSENTO;
ALTER TABLE VENDA ADD CONSTRAINT FK_ASSENTO FOREIGN KEY (ASSENTO) REFERENCES ASSENTO(ID_ASSENTO) ON DELETE CASCADE;

ALTER TABLE VENDA DROP CONSTRAINT FK_PAGAMENTO;
ALTER TABLE VENDA
ADD CONSTRAINT FK_PAGAMENTO FOREIGN KEY (PAGAMENTO) REFERENCES METODO_PAGAMENTO(ID_METODO_PAGAMENTO) ON DELETE CASCADE;


------ MAPA DE ASSENTOS
ALTER TABLE ASSENTO DROP CONSTRAINT FK_ID_VOO;
ALTER TABLE ASSENTO
ADD CONSTRAINT FK_ID_VOO FOREIGN KEY(ID_VOO) REFERENCES VOO(ID_VOO) ON DELETE CASCADE;

ALTER TABLE COMPANHIA_AEREA RENAME COLUMN ID_COMPANHIA TO ID_COMPANHIA_AEREA;

ALTER TABLE MAPA_ASSENTO RENAME TO ASSENTO;

ALTER TABLE METODO_PAGAMENTO RENAME COLUMN ID_METODO TO ID_METODO_PAGAMENTO;

--- TRIGGER  para gerar os assentos de um voo
CREATE OR REPLACE TRIGGER TRG_GERAR_ASSENTOS
AFTER INSERT ON VOO
FOR EACH ROW
DECLARE
    v_num_assentos NUMBER;
    v_coluna NUMBER;
BEGIN
    -- Obtem o número de assentos da aeronave associada ao voo
    SELECT NUMASSENTOS INTO v_num_assentos FROM AERONAVE
    WHERE ID_AERONAVE = :NEW.AERONAVE;

    -- Metade dos assentos para cada coluna
    v_coluna := (v_num_assentos / 2);

    -- Insere os assentos para o novo voo, pegando o id desse voo e cadastra o codigo do assento
    FOR i IN 1..v_coluna LOOP
        INSERT INTO ASSENTO(ID_ASSENTO, ID_VOO, CODIGO)
        VALUES (ID_MAPA_SEQ.nextval, :NEW.ID_VOO,'A' || TO_CHAR(i));
        INSERT INTO ASSENTO(ID_ASSENTO, ID_VOO, CODIGO)
        VALUES (ID_MAPA_SEQ.nextval, :NEW.ID_VOO, 'B' || TO_CHAR(i));
    END LOOP;
END;

--------------TESTE TRIGGER
INSERT INTO AERONAVE (MODELO, NUM_IDENTIFICACAO, FABRICANTE, ANO_FABRICACAO, COMPANHIA_AEREA)
VALUES ('Modelo1', 'Identificacao1', 'Fabricante1', 2022, 3);

INSERT INTO AERONAVE (MODELO, NUM_IDENTIFICACAO, FABRICANTE, ANO_FABRICACAO, COMPANHIA_AEREA)
VALUES ('Modelo2', 'Identificacao2', 'Fabricante2', 2021, 10);

delete from AERONAVE;
-- Inserindo uma linha na tabela VOO usando o NUM_IDENTIFICACAO 'Identificacao1'
INSERT INTO VOO (ID_VOO, DATA, TRECHO, HORA_PARTIDA, HORA_CHEGADA, PRECO, AERONAVE)
VALUES (1, SYSDATE, 49, '08:00', '12:00', 1000, 'Identificacao1');

DELETE FROM VOO WHERE ID_VOO= 1;
—versão 1 com as sequences ==========================================
----------- AERONAVE
CREATE TABLE AERONAVE(
    MODELO VARCHAR(20) NOT NULL,
    NUM_IDENTIFICACAO VARCHAR(20) NOT NULL PRIMARY KEY ,
    FABRICANTE VARCHAR (20) NOT NULL,
    ANO_FABRICACAO INTEGER NOT NULL,
    MAPA_ASSENTO INTEGER NOT NULL,
    COMPANHIA_AEREA INTEGER NOT NULL
);


ALTER TABLE AERONAVE
ADD CONSTRAINT FK_COMPANHIA_AEREA FOREIGN KEY(COMPANHIA_AEREA) REFERENCES COMPANHIA_AEREA(ID_COMPANHIA);

ALTER TABLE AERONAVE ADD ID_AERONAVE INTEGER NOT NULL;

ALTER TABLE AERONAVE DROP PRIMARY KEY;
ALTER TABLE AERONAVE ADD CONSTRAINT PK_ID_AERONAVE PRIMARY KEY (ID_AERONAVE);

CREATE SEQUENCE ID_AERONAVE_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 9999 NOCYCLE NOCACHE;
--------- AEROPORTO
CREATE TABLE AEROPORTO (
ID_AEROPORTO INTEGER NOT NULL PRIMARY KEY,
ID_CIDADE INTEGER NOT NULL,
NOME_AEROPORTO VARCHAR(35) NOT NULL
);

CREATE SEQUENCE ID_AEROPORTO_SEQ START WITH 001 INCREMENT BY 1 MAXVALUE 9999 NOCYCLE NOCACHE;

ALTER TABLE AEROPORTO
ADD CONSTRAINT FK_ID_CIDADE FOREIGN KEY(ID_CIDADE) REFERENCES CIDADE(ID_CIDADE);

ALTER TABLE AEROPORTO MODIFY SIGLA VARCHAR(8)  NOT NULL;

UPDATE AEROPORTO
SET SIGLA = 'SSA'
WHERE ID_AEROPORTO = 1;

UPDATE AEROPORTO
SET SIGLA = 'VCP'
WHERE ID_AEROPORTO = 4;

----------- CIDADE
CREATE TABLE CIDADE (
ID_CIDADE INTEGER NOT NULL PRIMARY KEY,
NOME_CIDADE VARCHAR(35) NOT NULL
);

delete from CIDADE where ID_CIDADE='2';

CREATE SEQUENCE ID_CIDADE_SEQ START WITH 001 INCREMENT BY 1 MAXVALUE 9999 NOCYCLE NOCACHE;

------------ TRECHO
CREATE TABLE TRECHO (
ID_TRECHO INTEGER NOT NULL PRIMARY KEY,
CIDADE_SAIDA INTEGER  NOT NULL,
CIDADE_CHEGADA INTEGER NOT NULL
);

CREATE SEQUENCE ID_TRECHO_SEQ START WITH 001 INCREMENT BY 1 MAXVALUE 9999 NOCYCLE NOCACHE;

ALTER TABLE TRECHO
ADD CONSTRAINT FK_CIDADE_SAIDA FOREIGN KEY(CIDADE_SAIDA) REFERENCES CIDADE(ID_CIDADE);

ALTER TABLE TRECHO
ADD CONSTRAINT FK_CIDADE_CHEGADA FOREIGN KEY(CIDADE_CHEGADA) REFERENCES CIDADE(ID_CIDADE);

-------------- VOO
CREATE TABLE VOO (
ID_VOO INTEGER NOT NULL PRIMARY KEY,
DATA DATE NOT NULL ,
TRECHO INTEGER NOT NULL,
HORA_PARTIDA VARCHAR(5) NOT NULL,
HORA_CHEGADA VARCHAR(5) NOT NULL,
PRECO NUMBER(10) NOT NULL,
AERONAVE VARCHAR(20) NOT NULL
);

CREATE SEQUENCE ID_VOO_SEQ START WITH 001 INCREMENT BY 1 MAXVALUE 9999 NOCYCLE NOCACHE;

ALTER TABLE VOO MODIFY AERONAVE INTEGER;

-------------- MAPA ASSENTO
CREATE TABLE MAPA_ASSENTO (
ID_ASSENTO INTEGER NOT NULL PRIMARY KEY,
ID_VOO INTEGER NOT NULL,
CODIGO INTEGER NOT NULL,
STATUS VARCHAR(15) DEFAULT 'DISPONIVEL'
);

CREATE SEQUENCE ID_MAPA_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 9999 NOCYCLE NOCACHE;
DROP SEQUENCE ID_MAPA_SEQ;

ALTER TABLE MAPA_ASSENTO
ADD CONSTRAINT FK_ID_VOO FOREIGN KEY(ID_VOO) REFERENCES VOO(ID_VOO);

ALTER TABLE MAPA_ASSENTO
MODIFY ID_VOO INTEGER NULL;

ALTER TABLE MAPA_ASSENTO
MODIFY COD_ASSENTO VARCHAR(3);
---renomeando colunas
ALTER TABLE MAPA_ASSENTO RENAME COLUMN ID_RESERVA TO ID_ASSENTO;

ALTER TABLE MAPA_ASSENTO RENAME COLUMN COD_ASSENTO TO CODIGO;
DELETE FROM MAPA_ASSENTO;

------------- VENDA
CREATE TABLE VENDA(
ID_VENDA INTEGER NOT NULL PRIMARY KEY,
NOME_PASSAGEIRO VARCHAR(50) NOT NULL ,
EMAIL_PASSAGEITO VARCHAR(50) NOT NULL ,
ASSENTO INTEGER NOT NULL ,
ID_VOO INTEGER NOT NULL,
PAGAMENTO INTEGER NOT NULL
);

CREATE SEQUENCE ID_VENDA_SEQ START WITH 001 INCREMENT BY 1 MAXVALUE 9999 NOCYCLE NOCACHE;

ALTER TABLE VENDA
ADD CONSTRAINT FK_ID_VOO FOREIGN KEY (ID_VOO) REFERENCES VOO(ID_VOO);

ALTER TABLE VENDA
ADD CONSTRAINT FK_PAGAMENTO FOREIGN KEY (PAGAMENTO) REFERENCES METODO_PAGAMENTO(ID_METODO_PAGAMENTO);

alter table VENDA rename column EMAIL_PASSAGEITO to EMAIL_PASSAGEIRO;

ALTER TABLE VENDA MODIFY ASSENTO INTEGER;


--------------- METODOS DE PAGAMENTO
CREATE TABLE METODO_PAGAMENTO(
ID_METODO INTEGER NOT NULL PRIMARY KEY,
NOME_METODO VARCHAR(20) NOT NULL
);
drop sequence ID_METODO_SEQ;
CREATE SEQUENCE ID_METODO_SEQ START WITH 3 INCREMENT BY 1 MAXVALUE 9999 NOCYCLE NOCACHE;

------------------ COMPANHIA AEREA
CREATE TABLE COMPANHIA_AEREA (
ID_COMPANHIA INTEGER NOT NULL PRIMARY KEY,
NOME_COMPANHIA VARCHAR (15) NOT NULL
);

CREATE SEQUENCE ID_COMPANHIA_SEQ START WITH 001 INCREMENT BY 1 MAXVALUE 9999 NOCYCLE NOCACHE;
