
----------- CIDADE
CREATE TABLE CIDADE (
ID_CIDADE INTEGER NOT NULL PRIMARY KEY,
NOME_CIDADE VARCHAR(35) NOT NULL
);


CREATE SEQUENCE ID_CIDADE_SEQ START WITH 001 INCREMENT BY 1 MAXVALUE 9999 NOCYCLE NOCACHE;
