
------------------ COMPANHIA AEREA
CREATE TABLE COMPANHIA_AEREA (
ID_COMPANHIA INTEGER NOT NULL PRIMARY KEY,
NOME_COMPANHIA VARCHAR (15) NOT NULL
);

CREATE SEQUENCE ID_COMPANHIA_SEQ START WITH 001 INCREMENT BY 1 MAXVALUE 9999 NOCYCLE NOCACHE;