create table test(
    test_id integer not null,
    test_name varchar2(10) Not NULL,
    PRIMARY KEY(test_id)
)

select * from test

insert into test values (1, 'nat')

----------- AERONAVE
CREATE TABLE AERONAVE(
    MODELO VARCHAR(20) NOT NULL,
    NUMIDENTIFICACAO VARCHAR(20) NOT NULL PRIMARY KEY ,
    FABRICANTE VARCHAR (20) NOT NULL,
    ANOFABRICACAO INTEGER NOT NULL,
    MAPA_ASSENTO INTEGER NOT NULL,
    COMPANHIA_AEREA INTEGER NOT NULL
);

ALTER TABLE AERONAVE
ADD CONSTRAINT FK_MAPA_ASSENTO FOREIGN KEY(MAPA_ASSENTO) REFERENCES MAPA_ASSENTO(ID_MAPA);

ALTER TABLE AERONAVE
ADD CONSTRAINT FK_COMPANHIA_AEREA FOREIGN KEY(COMPANHIA_AEREA) REFERENCES COMPANHIA_AEREA(ID_COMPANHIA);


--------- AEROPORTO
CREATE TABLE AEROPORTO (
ID_AEROPORTO INTEGER NOT NULL PRIMARY KEY,
ID_CIDADE INTEGER NOT NULL,
NOME_AEROPORTO VARCHAR(35) NOT NULL
);

CREATE SEQUENCE ID_AEROPORTO_SEQ START WITH 001 INCREMENT BY 1 MAXVALUE 9999 NOCYCLE NOCACHE;

ALTER TABLE AEROPORTO
ADD CONSTRAINT FK_ID_CIDADE FOREIGN KEY(ID_CIDADE) REFERENCES CIDADE(ID_CIDADE);

----------- CIDADE
CREATE TABLE CIDADE (
ID_CIDADE INTEGER NOT NULL PRIMARY KEY,
NOME_CIDADE VARCHAR(35) NOT NULL
);


CREATE SEQUENCE ID_CIDADE_SEQ START WITH 001 INCREMENT BY 1 MAXVALUE 9999 NOCYCLE NOCACHE;

------------ TRECHO
CREATE TABLE TRECHO (
ID_TRECHO INTEGER NOT NULL PRIMARY KEY,
CIDADE_SAIDA INTEGER  NOT NULL,
CIDADE_CHEGADA INTEGER NOT NULL
);

CREATE SEQUENCE ID_TRECHO_SEQ START WITH 001 INCREMENT BY 1 MAXVALUE 9999 NOCYCLE NOCACHE;

ALTER TABLE TRECHO
ADD CONSTRAINT FK_CIDADE_SAIDA FOREIGN KEY(CIDADE_SAIDA) REFERENCES CIDADE(ID_CIDADE);

ALTER TABLE TRECHO
ADD CONSTRAINT FK_CIDADE_CHEGADA FOREIGN KEY(CIDADE_CHEGADA) REFERENCES CIDADE(ID_CIDADE);

-------------- VOO
CREATE TABLE VOO (
ID_VOO INTEGER NOT NULL PRIMARY KEY,
DATA DATE NOT NULL ,
TRECHO INTEGER NOT NULL,
HORA_PARTIDA VARCHAR(5) NOT NULL,
HORA_CHEGADA VARCHAR(5) NOT NULL,
AEROPORTO_IDA INTEGER NOT NULL,
AEROPORTO_VOLTA INTEGER NOT NULL  ,
PRECO NUMBER(10) NOT NULL,
AERONAVE VARCHAR(20) NOT NULL,
FOREIGN KEY (TRECHO) REFERENCES TRECHO(ID_TRECHO),
FOREIGN KEY (AEROPORTO_IDA) REFERENCES AEROPORTO(ID_AEROPORTO),
FOREIGN KEY (AEROPORTO_VOLTA) REFERENCES AEROPORTO(ID_AEROPORTO),
FOREIGN KEY (AERONAVE) REFERENCES AERONAVE(NUMIDENTIFICACAO)
);

CREATE SEQUENCE ID_VOO_SEQ START WITH 001 INCREMENT BY 1 MAXVALUE 9999 NOCYCLE NOCACHE;

-------------- MAPA ASSENTO
CREATE TABLE MAPA_ASSENTO (
ID_MAPA INTEGER NOT NULL PRIMARY KEY,
NUM_DE_FILEIRA INTEGER NOT NULL ,
NUM_POR_FILEIRA INTEGER NOT NULL
);

CREATE SEQUENCE ID_MAPA_SEQ START WITH 001 INCREMENT BY 1 MAXVALUE 9999 NOCYCLE NOCACHE;

-------------- VENDA
CREATE TABLE VENDA(
ID_VENDA INTEGER NOT NULL PRIMARY KEY,
NOME_PASSAGEIRO VARCHAR(50) NOT NULL ,
EMAIL_PASSAGEITO VARCHAR(50) NOT NULL ,
ASSENTO VARCHAR (6) NOT NULL ,
ID_VOO INTEGER NOT NULL,
PAGAMENTO INTEGER NOT NULL
);

CREATE SEQUENCE ID_VENDA_SEQ START WITH 001 INCREMENT BY 1 MAXVALUE 9999 NOCYCLE NOCACHE;

ALTER TABLE VENDA
ADD CONSTRAINT FK_ID_VOO FOREIGN KEY (ID_VOO) REFERENCES VOO(ID_VOO);

ALTER TABLE VENDA
ADD CONSTRAINT FK_PAGAMENTO FOREIGN KEY (PAGAMENTO) REFERENCES METODO_PAGAMENTO(ID_METODO);

--------------- METODOS DE PAGAMENTO
CREATE TABLE METODO_PAGAMENTO(
ID_METODO INTEGER NOT NULL PRIMARY KEY,
NOME_METODO VARCHAR(20) NOT NULL
);

CREATE SEQUENCE ID_METODO_SEQ START WITH 001 INCREMENT BY 1 MAXVALUE 9999 NOCYCLE NOCACHE;

------------------ COMPANHIA AEREA
CREATE TABLE COMPANHIA_AEREA (
ID_COMPANHIA INTEGER NOT NULL PRIMARY KEY,
NOME_COMPANHIA VARCHAR (15) NOT NULL
);

CREATE SEQUENCE ID_COMPANHIA_SEQ START WITH 001 INCREMENT BY 1 MAXVALUE 9999 NOCYCLE NOCACHE;
