
------------ TRECHO
CREATE TABLE TRECHO (
ID_TRECHO INTEGER NOT NULL PRIMARY KEY,
CIDADE_SAIDA INTEGER  NOT NULL,
CIDADE_CHEGADA INTEGER NOT NULL
);

CREATE SEQUENCE ID_TRECHO_SEQ START WITH 001 INCREMENT BY 1 MAXVALUE 9999 NOCYCLE NOCACHE;

ALTER TABLE TRECHO
ADD CONSTRAINT FK_CIDADE_SAIDA FOREIGN KEY(CIDADE_SAIDA) REFERENCES CIDADE(ID_CIDADE);

ALTER TABLE TRECHO
ADD CONSTRAINT FK_CIDADE_CHEGADA FOREIGN KEY(CIDADE_CHEGADA) REFERENCES CIDADE(ID_CIDADE);
