
-------------- VENDA
CREATE TABLE VENDA(
ID_VENDA INTEGER NOT NULL PRIMARY KEY,
NOME_PASSAGEIRO VARCHAR(50) NOT NULL ,
EMAIL_PASSAGEITO VARCHAR(50) NOT NULL ,
ASSENTO VARCHAR (6) NOT NULL ,
ID_VOO INTEGER NOT NULL,
PAGAMENTO INTEGER NOT NULL
);

CREATE SEQUENCE ID_VENDA_SEQ START WITH 001 INCREMENT BY 1 MAXVALUE 9999 NOCYCLE NOCACHE;

ALTER TABLE VENDA
ADD CONSTRAINT FK_ID_VOO FOREIGN KEY (ID_VOO) REFERENCES VOO(ID_VOO);

ALTER TABLE VENDA
ADD CONSTRAINT FK_PAGAMENTO FOREIGN KEY (PAGAMENTO) REFERENCES METODO_PAGAMENTO(ID_METODO);
