
-------------- VOO
CREATE TABLE VOO (
ID_VOO INTEGER NOT NULL PRIMARY KEY,
DATA DATE NOT NULL ,
TRECHO INTEGER NOT NULL,
HORA_PARTIDA VARCHAR(5) NOT NULL,
HORA_CHEGADA VARCHAR(5) NOT NULL,
PRECO NUMBER(10) NOT NULL,
AERONAVE VARCHAR(20) NOT NULL,
FOREIGN KEY (TRECHO) REFERENCES TRECHO(ID_TRECHO),
FOREIGN KEY (AERONAVE) REFERENCES AERONAVE(NUM_IDENTIFICACAO)
);

CREATE SEQUENCE ID_VOO_SEQ START WITH 001 INCREMENT BY 1 MAXVALUE 9999 NOCYCLE NOCACHE;
